import sql from "@/app/api/utils/sql";

export async function POST(request) {
  try {
    // Check for API key
    if (!process.env.OPENAI_API_KEY) {
      return Response.json(
        {
          error:
            "OpenAI API key not configured. Please add OPENAI_API_KEY to your environment variables.",
        },
        { status: 500 },
      );
    }

    const body = await request.json();
    const { topic, category, ticketPattern } = body;

    if (!topic && !ticketPattern) {
      return Response.json(
        { error: "Topic or ticket pattern is required" },
        { status: 400 },
      );
    }

    let contextData = "";
    let runbookTitle = topic || "Operational Procedure";

    // If generating from ticket pattern, analyze similar tickets
    if (ticketPattern) {
      const similarTickets = await sql`
        SELECT * FROM tickets
        WHERE 
          (title ILIKE ${`%${ticketPattern}%`} OR description ILIKE ${`%${ticketPattern}%`})
          AND status = 'Resolved'
          AND resolution_notes IS NOT NULL
        ORDER BY resolved_at DESC
        LIMIT 10
      `;

      if (similarTickets.length > 0) {
        runbookTitle = `Runbook: ${ticketPattern}`;
        contextData = `
Historical Resolutions (Based on ${similarTickets.length} similar resolved tickets):

${similarTickets
  .map(
    (t, i) => `
Resolution ${i + 1}:
- Ticket: ${t.ticket_number}
- Title: ${t.title}
- Severity: ${t.severity}
- Resolution: ${t.resolution_notes}
- Time to Resolve: ${t.time_to_resolve_hours ? `${t.time_to_resolve_hours}h` : "N/A"}
`,
  )
  .join("\n")}
`;
      }
    }

    const prompt = `You are an AI runbook generator for e-Portal InfraHub. Create a comprehensive, step-by-step operational runbook.

Runbook Topic: ${runbookTitle}
Category: ${category || "General Operations"}

${contextData}

Generate a professional runbook following this structure:

# ${runbookTitle}

## Overview
[Brief description of when to use this runbook and what it accomplishes]

## Prerequisites
- Required access/permissions
- Required tools/utilities
- Required knowledge/skills
- Estimated time to complete

## Severity Assessment
| Severity | Indicators | Response Time |
|----------|-----------|---------------|
| Critical | [symptoms] | Immediate |
| High | [symptoms] | 1 hour |
| Medium | [symptoms] | 4 hours |

## Step-by-Step Procedure

### Phase 1: Initial Assessment (5-10 minutes)
1. **Verify the issue**
   - [ ] Specific check or command
   - [ ] Expected result
   - [ ] What to look for

2. **Gather diagnostic information**
   - [ ] Command or log to check
   - [ ] Data to collect
   - [ ] Screenshots/evidence needed

### Phase 2: Diagnosis (10-20 minutes)
3. **Check common causes**
   - [ ] Most likely cause #1 - how to verify
   - [ ] Most likely cause #2 - how to verify
   - [ ] Most likely cause #3 - how to verify

4. **Run diagnostic commands**
   \`\`\`bash
   # Provide actual commands here
   \`\`\`

### Phase 3: Resolution (varies)
5. **Apply fix for [Scenario A]**
   - [ ] Detailed step
   - [ ] Verification command
   - [ ] Expected output

6. **Apply fix for [Scenario B]**
   - [ ] Detailed step
   - [ ] Verification command

### Phase 4: Verification (5-10 minutes)
7. **Confirm resolution**
   - [ ] Test to perform
   - [ ] Metric to check
   - [ ] User validation

8. **Document and close**
   - [ ] Update ticket with findings
   - [ ] Update CMDB if needed
   - [ ] Notify stakeholders

## Rollback Procedure
If resolution fails or causes issues:
1. [Step to revert]
2. [Step to restore]
3. [Escalation path]

## Escalation Path
- **Level 1:** Self-service (this runbook)
- **Level 2:** ${category === "Storage" ? "Storage Team Lead" : category === "VMware" ? "Virtualization Team" : "Senior Engineer"} (after 1 hour)
- **Level 3:** Vendor support (if no progress after 2 hours for Critical)
- **Level 4:** Management notification (for SLA risk)

## Related Documentation
- Link to architecture diagram
- Link to vendor KB article
- Link to internal wiki

## Common Pitfalls
- ⚠️ [Common mistake to avoid]
- ⚠️ [Another pitfall]

## Post-Incident Review
- [ ] Update this runbook if new info discovered
- [ ] Schedule preventive maintenance if needed
- [ ] Review with team in next standup

---
*Last Updated: ${new Date().toLocaleDateString()}*
*Generated by: AI Runbook Generator*

Make the runbook actionable, specific, and technically accurate. Use actual commands where possible. Include checkboxes for each step.`;

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: "gpt-4o",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.4,
        max_tokens: 3000,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("OpenAI API error:", response.status, errorText);
      throw new Error(
        `OpenAI API request failed: ${response.status} ${response.statusText}`,
      );
    }

    const data = await response.json();
    const runbook = data.choices[0].message.content;

    return Response.json({
      runbook,
      title: runbookTitle,
      category: category || "General",
    });
  } catch (error) {
    console.error("Error generating runbook:", error);
    return Response.json(
      { error: error.message || "Failed to generate runbook" },
      { status: 500 },
    );
  }
}
